name: Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  sonarqube:
    name: Sonarscan
    uses: SonarSource/sonarqube-scan-action@v6
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
