name: Build

on:
  push:
    branches:
      - master
      - dev
      - QA

jobs:
   build:
     name: Build and analyze with shared workflow
     uses: Practice-org04651/sonar-main/.github
     secrets:
       SONAR_TOKEN: ${{ secrets.MSQToken }}
       SONAR_HOST_URL: ${{ secrets.SONAR_HO
       SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
