name: Build

on:
  push:
    branches:
      - master
      - Dev

jobs:
   sonarqube:
    name: Sonarscan
    uses: Practice-org04651/sonar-main/.github/workflows/sonarqube-build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
